### ISSUE TITLE
feat(jrgen-spec): allow to define default server urls

### ISSUE THREAD

**Issue by mzernetsch** [mzernetsch/jrgen#10]
There should be a 'servers' property similar to the one in the [OpenAPI-Specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject) which allows to define default server urls.

These server urls will be used in the following places:
- docs/md: list of available servers near the general description area.
- docs/html: list of available servers near the general description area.
- docs/html: default url when sending requests. 
- test/jasmine: default url for tests. 
- test/postman: default value for environment variable {{url}}

**Comment by rainchen** [comment]
+1 for this feature

**Comment by alexjonser** [comment]
+1 for this feature
