### ISSUE TITLE
support for OpenAPI v3 export

### ISSUE THREAD

**Issue by BrannonKing** [mzernetsch/jrgen#12]
I see some comments about trying to stay in step with OpenAPI. Has there been any work done to generate valid OpenAPI v3 from a given API in jrgen's schema?

**Comment by mzernetsch** [comment]
I thought about adding an openapi generator to the recent release but then i remembered why jrgen actually exists. 

Before i created this tool i tried to describe json rpc apis using openapi specs. The big problem with this is the fundamental difference in the architectures rest vs jsonrpc. While rest is designed to have multiple endpoints (one for every "method" basically), jsonrpc has just one endpoint where you send all your requests to.

So an OpenAPI spec describing a jsonrpc api would essentially look like this:
```yaml
paths:
  /jsonrpc:
    post:
      summary: ''
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/definitions/methods/Session.Login/request'
                - $ref: '#/definitions/methods/Session.Logout/request'
                - $ref: '#/definitions/methods/Session.KeepAlive/request'
                - ...
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/definitions/methods/Session.Login/response'
                - $ref: '#/definitions/methods/Session.Logout/response'
                - $ref: '#/definitions/methods/Session.KeepAlive/response'
                - ...
```

While this would technically describe the api, i don't think you can do anything really useful with it.

**Comment by BrannonKing** [comment]
That makes sense. Is it also true for CoreAPI and jsonapi.org?

**Comment by mzernetsch** [comment]
I personally never worker with either of those.
At a first glance i would say that jsonapi has the same problem. 
CoreAPI though seems to have a more general approach that could be useful.

Do you have some experience using these tools with jsonrpc?
