### ISSUE TITLE
Feature request: support of a scoped plugins

### ISSUE THREAD

**Issue by ivankhm** [mzernetsch/jrgen#18]
Hi! I would like to make a feature request.

Right now you can only use plugins, that have their name begin with `jrgen` (according to source code and the docs).

Is it possible to make it so, that you can use package names like `@my-org/jrgen-plugin-stuff`?
The reason behind this - I need to use it in a private repo, with a private package registry on GitLab. And it's not possible, to deploy packages without specifying the root scope. 

The only workaround for my environment - is to just fork jrgen and customize it as a hole.

**Comment by mzernetsch** [comment]
I released a new version (3.1.0) which adds support for scope folders.

jrgen now uses the following glob pattern to find plugins: `{@**/,}jrgen*/**/*.jrgen.blueprint.js`
