### ISSUE TITLE
Option '-o' '--output-dir' is broken

### ISSUE THREAD

**Issue by helmut-arch** [mzernetsch/jrgen#31]
This seems to be a regression from 3.3.0: the 

When installing globally jrgen at the latest version (3.3.0):

`$ npm install -g jrgen
`npm WARN deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser
`
`added 101 packages in 9s
`
`20 packages are looking for funding
`  run `npm fund` for details
`
`$ jrgen --version
`3.3.0

Outputting to a directory fails:
`$ jrgen docs-html -o ./html example.json
`error: unknown option '-o'

But when downgrading to 3.2.0 (still globally):
`$ npm install -g jrgen@3.2.0
`npm WARN deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser
`
`added 55 packages in 9s
`
`3 packages are looking for funding
`  run `npm fund` for details
`
`$ jrgen --version
`3.2.0
`
It works just fine:
`$ jrgen docs-html -o ./html example.json
`
`$ 

OS: Windows 10 Enterprise

**Comment by mzernetsch** [comment]
I just tried the command `jrgen docs-html -o ./html ./ExampleAPI.jrgen.json` on version 3.3.0 successfully on my machine (Arch Linux). A similar command  actually runs inside the ci pipeline on every commit so it _should_ not be possible to release a new version if that parameter was broken.

The only difference between the mentioned versions regarding this parameter would be an upgrade of the commander dependency from 9.x.x to 11.0.0. Looking at the commander commit history at first glance i can't find anything relevant to your issue: https://github.com/tj/commander.js/compare/v9.5.0...v11.0.0

Are you sure there was no problem in your test like a weird whitespace character or something like that?
