### ISSUE TITLE
How can I use my custom generators and templates instead of default ones?

### ISSUE THREAD

**Issue by bevalorous** [mzernetsch/jrgen#7]
Built-in templates and generators are awesome. However I need to generate docs for my project with a structure that differs from default one: other order of fields, other TOC, etc. 

Is there any way to override default templates and generators with my custom ones?

P.S. Of course, I can fork your repo and edit generators and templates in my copy, but I don't like this way :-)

**Comment by mzernetsch** [comment]
I pushed a small commit (1c07913306762ecacdc6a31112186cee019b652a) which introduces a simple plugin system. I need to document this properly sometime in the future. 

Basically a plugin is a npm module which has a name starting with `jrgen-plugin-`. You need to install this module as a sibling to jrgen (`npm i -g jrgen jrgen-plugin-mymodule`). jrgen expects this module to contain a "generators" folder in which you can define custom generators or override the existing ones. The logic is similar to the main jrgen module so a path to a generator would look like this: `jrgen-plugin-mymodule/generators/docs/html/generator.js`.

Would you be able to do some testing before i publish a new npm package? You would need to install the current build from github.

**Comment by Zapata** [comment]
I can confirm the plugin mechanism works. I have tested it [there](https://github.com/Zapata/bitshares-api-schema). You can see in the [Dockerfile](https://github.com/Zapata/bitshares-api-schema/blob/master/Dockerfile#L5) how I used it.
