### ISSUE TITLE
Support tuples validation for array.

### ISSUE THREAD

**Issue by Zapata** [mzernetsch/jrgen#8]
Please support [tuple validation](https://spacetelescope.github.io/understanding-json-schema/reference/array.html?highlight=array%20tuples#tuple-validation).

**Comment by Zapata** [comment]
I made an attempt to support them [here](https://github.com/Zapata/bitshares-api-schema/blob/master/jrgen-plugin-bitshares/generators/docs/html/generator.js#L213) and [there](https://github.com/Zapata/bitshares-api-schema/blob/master/jrgen-plugin-bitshares/generators/docs/html/utils.js#L97).  Tell me if you want me to do a PR.

**Comment by mzernetsch** [comment]
I did my own implementation based on your code where i basically added the following:
- name property is optional
- support in markdown generator
- keep code dry between html and md generator

The only difference right now between the main html generator and your custom generator should be the default_url. We could add something like this in the main generator so there wouldn't be any need for a custom plugin.

**Comment by Zapata** [comment]
Excellent, thanks.

default_url could be nice indeed. Do you want me to create an issue?

**Comment by mzernetsch** [comment]
I created a new issue for this (#10). I try to keep the jrgen-spec aligned to the openapi-spec whenever possible and reasonable, so i would like to use a 'servers' property instead of 'default_url'.
